data_dirpath: "/home/renat/data/rgbd-kinect-pose"
output_dirpath: "/home/renat/Desktop/kavatar_test"


aggregate:  # aggregate results from body, hand and face blocks
  log_level: 1
  gender: "male"  # which gender and shape to use for visualization and filtering
  person_shape_path: "shapefit/renat"
  vis_pose:
    enable: True
    imshow: True
    imsave: False
    scale: .2  # reduce resolution for real-time visualization
    device: "cuda:0"  # must be cuda: minimal_pytorch_rasterizer for mesh visualizaion does not support cpu
  filterer:
    device: "cpu"  # for smplx inference
    modify_wrist: False  # True value provides good result only on slow motions with a clear background
    modify_wrist_th: 0.05
    modify_wrist_N: 10
    filter_wrist: True  # wrist here is a body joint to which hand is attached
    filter_hand: True  # filter each of 15 joints for each hand
    filter_global_trans: True  # global translation for body
    filter_global_rot: True  # global rotation for body
    filter_body_pose: True  # filter 21 joints of body
    filter_jaw_pose: True  # filter single jaw joint
    filter_face_expression: True  # filter 10 face expression parameters
    fix_global: False

k4a: # kinect streaming block
  log_level: 2
  dump_fp: null
#  dump_fp: "/storage/wacv_publish/pyk4a_dump/test.pickle"
  skip_old: False
  fps: 30
  parallel_bt: True
  gpu_id: 0

hand_pose:
  enable: True
  log_level: 1
  hand_mesh_model_path: "minimal_hand/model/hand_mesh/hand_mesh_model.pkl"
  detection_model_path: "minimal_hand/model/detnet/detnet.ckpt"
  ik_model_path: "minimal_hand/model/iknet/iknet.ckpt"
  gpu_id: 0

face_pose:
  enable: True
  log_level: 1
  config_path: "face_expression/04/config.yaml"
  checkpoint_path: "face_expression/04/checkpoint_000044.pth"
  device: "cpu"

body_pose:
  log_level: 1
  model_path: "smplx_kinect/04"
  checkpoint: 110000
  gender: "male"  # gender and shape of a person that is in front of the camera
  person_shape_path: "shapefit/renat"
  device: "cuda:0"
